concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ec04f0bdecc5"
  url = "http://lab.tog.co.id/"
  token = "QXissAWZToTQFdK4pWiz"
  executor = "docker"
  environment = ["TZ=Asia/Jakarta", "COMPOSER_HOME=/root/.composer"]
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    cpus = "2"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/opt/data/gitlab/cache/maven:/root/.m2:rw", "/opt/data/gitlab/cache/gradle:/root/.gradle:rw", "/opt/data/gitlab/cache/npm:/root/.npm:rw", "/opt/data/gitlab/cache/yarn:/root/.yarn:rw", "/opt/data/gitlab/cache/composer:/root/.composer:rw", "/cache"]
    extra_hosts = ["lab.tog.co.id:172.20.4.10"]
    shm_size = 0
    pull_policy = "if-not-present"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""
