version: '3.6'
networks:
  gitlab:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
    name: gitlab
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: ${DOMAIN_NAME}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${SSH_PORT:-22}:22"
    volumes:
      - ${GITLAB_DATA:-./data/gitlab}/config:/etc/gitlab
      - ${GITLAB_DATA:-./data/gitlab}/logs:/var/log/gitlab
      - ${GITLAB_DATA:-./data/gitlab}/data:/var/opt/gitlab
    environment:
      TZ: "Asia/Jakarta"
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${PROTOCOL}://${DOMAIN_NAME}"
        gitlab_rails["smtp_enable"] = true
        gitlab_rails["smtp_address"] = "smtp.gmail.com"
        gitlab_rails["smtp_port"] = 587
        gitlab_rails["smtp_user_name"] = "${GMAIL_USER}"
        gitlab_rails["smtp_password"] = "${GMAIL_PASS}"
        gitlab_rails["smtp_domain"] = "smtp.gmail.com"
        gitlab_rails["smtp_authentication"] = "login"
        gitlab_rails["smtp_enable_starttls_auto"] = true
        gitlab_rails["smtp_tls"] = false
        gitlab_rails["smtp_openssl_verify_mode"] = "peer"
    networks:
      gitlab:
        ipv4_address: 172.16.238.2
        aliases:
          - ${DOMAIN_NAME}
  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./data/gitlab/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Jakarta
      - REGISTER_LOCKED=false
    networks:
      gitlab:
        ipv4_address: 172.16.238.3
    extra_hosts:
      - "${DOMAIN_NAME}:172.16.238.2"
