version: '3.6'
networks:
  gitlab:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
    name: gitlab
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: lab.tog.co.id
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${SSH_PORT:-22}:22"
    volumes:
      - /opt/data/gitlab/config:/etc/gitlab
      - /opt/data/gitlab/logs:/var/log/gitlab
      - /opt/data/gitlab/data:/var/opt/gitlab
    environment:
      TZ: "Asia/Jakarta"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://lab.tog.co.id'
    networks:
      gitlab:
        ipv4_address: 172.16.238.2
        aliases:
          - lab.tog.co.id
  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./data/gitlab/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Jakarta
      - REGISTER_LOCKED=false
    networks:
      gitlab:
        ipv4_address: 172.16.238.3
    extra_hosts:
      - "lab.tog.co.id:172.16.238.2"
